const STATE_TRANSITIONS = {
  PENDING_DOCTOR: ["ACCEPTED", "REJECTED"],
  ACCEPTED: ["CANCELLED_BY_PATIENT"],
  REJECTED: [],
  EXPIRED: [],
  CANCELLED_BY_PATIENT: []
};

module.exports = STATE_TRANSITIONS;
